all:
	gcc question_a_1.c -o question_a_1 -pthread
	gcc question_a_2.c -o question_a_2 -pthread
	
	gcc question_b_1.c -o question_b_1 -pthread
	gcc question_b_2.c -o question_b_2 -pthread


clean:
	rm ./question_a_1
	rm ./question_a_2
	rm ./question_b_1
	rm ./question_b_2